# docker-compose.yml

#version: '3'

services:
  proxy:
    container_name: proxy
    image: nginx:1.25
    ports:
      - 443:443
    volumes:
      - /etc/letsencrypt/live/upstream-dso.tacc.utexas.edu/fullchain.pem:/root/ssl/cert.pem
      - /etc/letsencrypt/live/upstream-dso.tacc.utexas.edu/privkey.pem:/root/ssl/key.pem
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    container_name: web
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db:
    container_name: db
    image: postgis/postgis:16-3.4
    user: "${UIDGID}"
    volumes:
      - "${HOME}/pgdata:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
      - tasURL=https://tas-dev.tacc.utexas.edu/api-test
      - tasUser=tasclient
      - alg=HS256
    # some vars are in a file because they should not be checked in:
    # - POSTGRES_PASSWORD
    # - tasSecret
    # - jwtSecret
    env_file: 
      - /root/fastapi-env


