# docker-compose.yml

#version: '3'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    user: "${UIDGID}"
    volumes:
      - "${HOME}/pgdata:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
